version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: raizes_postgres
    environment:
      POSTGRES_DB: raizes_db
      POSTGRES_USER: raizes_app
      POSTGRES_PASSWORD: secret_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raizes_app -d raizes_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: raizes_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: raizes_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  api-backend:
    build: .
    container_name: raizes_backend_api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/raizes_db
      SPRING_DATASOURCE_USERNAME: raizes_app
      SPRING_DATASOURCE_PASSWORD: secret_password
      SPRING_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started

volumes:
  pgdata: