package com.raizes.nordeste.pedidos.infrastructure.audit;

public enum TipoEventoAuditoria {
    LOGIN,
    CHECKOUT_PEDIDO,
    ALTERACAO_STATUS_PEDIDO,
    CANCELAMENTO_PEDIDO,
    CONSULTA_FIDELIDADE,
    CONSENTIMENTO_FIDELIDADE_CONCEDIDO,
    CONSENTIMENTO_FIDELIDADE_REVOGADO,
    RESGATE_FIDELIDADE
}
