spring:
  application:
    name: raizes-nordeste-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/raizes_db}
    username: ${SPRING_DATASOURCE_USERNAME:raizes_app}
    password: ${SPRING_DATASOURCE_PASSWORD:secret_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Alinhado com Flyway para apenas validar a estrutura do banco
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html