spring:
  application:
    name: raizes-nordeste-backend
  datasource:
    url: jdbc:postgresql://postgres:5432/raizes_db
    username: postgres
    password: postgres_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: redis
      port: 6379
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html